name: CI/CD

on:
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Triggers on semantic version tags (1.0.0, 2.1.3, etc.)
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'webpack.config.cjs'
      - 'tsconfig.json'
      - 'jest.config.js'
      - 'eslint.config.js'
      - 'src/**'
      - 'test/**'
      - 'scripts/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'webpack.config.cjs'
      - 'tsconfig.json'
      - 'jest.config.js'
      - 'eslint.config.js'
      - 'src/**'
      - 'test/**'
      - 'scripts/**'

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Build nightly bundles via composite action
      id: nightly
      if: matrix.node-version == '20.x' && github.event_name != 'create'
      uses: ./.github/actions/project-build
      with:
        version: 0.0.0
        version-name: nightly-${{ github.sha }}
        node-version: '20'
        create-archives: 'false' # Only for nightly builds, to prevent double zips being uploaded

    - name: Upload nightly artifact - Chrome
      if: matrix.node-version == '20.x' && github.event_name != 'create'
      uses: actions/upload-artifact@v4
      with:
        name: AutoContinue-Chrome-nightly-${{ github.sha }}
        path: ${{ steps.nightly.outputs.chrome-path }}/
        if-no-files-found: error
        retention-days: 7

    - name: Upload nightly artifact - Firefox
      if: matrix.node-version == '20.x' && github.event_name != 'create'
      uses: actions/upload-artifact@v4
      with:
        name: AutoContinue-Firefox-nightly-${{ github.sha }}
        path: ${{ steps.nightly.outputs.firefox-path }}/
        if-no-files-found: error
        retention-days: 7

    - name: Upload nightly artifact - Safari
      if: matrix.node-version == '20.x' && github.event_name != 'create'
      uses: actions/upload-artifact@v4
      with:
        name: AutoContinue-Safari-nightly-${{ github.sha }}
        path: ${{ steps.nightly.outputs.safari-path }}/
        if-no-files-found: error
        retention-days: 7

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for proper tagging
          
      - name: Build project
        id: build
        uses: ./.github/actions/project-build
        with:
          version: ${{ github.ref_name }}
          node-version: '18'
          
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT }}
          name: AutoContinue ${{ steps.build.outputs.generated-version }}
          tag: ${{ github.ref_name }} 
          body: |
            
            ## Installation
            
            1. Download the appropriate extension for your browser (see `Assets` below)
            2. Extract the ZIP file
            3. Open your browser's extension management page
            4. Enable "Developer mode"
            5. Click "Load unpacked" and select the extracted folder
            
          artifacts: |
            release/AutoContinue-Chrome-${{ github.ref_name }}.zip
            release/AutoContinue-Firefox-${{ github.ref_name }}.zip
            release/AutoContinue-Safari-${{ github.ref_name }}.zip
          draft: true
          allowUpdates: true
          prerelease: ${{ steps.build.outputs.is-prerelease }}
