name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Triggers on semantic version tags (1.0.0, 2.1.3, etc.)

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper tagging
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update version from tag
        run: node scripts/version.js
        env:
          VERSION: ${{ github.ref_name }}
          
      - name: Run tests
        run: npm run test
        
      - name: Build all platforms
        run: |
          npm run build:chrome
          npm run build:firefox
          npm run build:safari
        env:
          VERSION: ${{ github.ref_name }}
          
      - name: Create release directory
        run: mkdir -p release
        
      - name: Package Chrome extension
        run: |
          cd dist
          zip -r ../release/AutoContinue-Chrome-${{ github.ref_name }}.zip .
          cd ..
          
      - name: Package Firefox extension
        run: |
          cd dist
          zip -r ../release/AutoContinue-Firefox-${{ github.ref_name }}.zip .
          cd ..
          
      - name: Package Safari extension
        run: |
          cd dist
          zip -r ../release/AutoContinue-Safari-${{ github.ref_name }}.zip .
          cd ..
          
      - name: Create source archive
        run: |
          git archive --format=zip --output=release/AutoContinue-Source-${{ github.ref_name }}.zip HEAD
          
      - name: Generate changelog
        id: changelog
        run: |
          # Get commits since last tag
          if git describe --tags --abbrev=0 HEAD~1 >/dev/null 2>&1; then
            PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1)
            CHANGELOG=$(git log --pretty=format:"- %s" $PREV_TAG..HEAD)
          else
            CHANGELOG=$(git log --pretty=format:"- %s" --max-count=20)
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: AutoContinue ${{ github.ref_name }}
          body: |
            ## What's New in ${{ github.ref_name }}
            
            ${{ steps.changelog.outputs.changelog }}
            
            ## Downloads
            
            ### Browser Extensions
            - **Chrome/Chromium**: [AutoContinue-Chrome-${{ github.ref_name }}.zip](https://github.com/sunnamed434/AutoContinue/releases/download/${{ github.ref_name }}/AutoContinue-Chrome-${{ github.ref_name }}.zip)
            - **Firefox**: [AutoContinue-Firefox-${{ github.ref_name }}.zip](https://github.com/sunnamed434/AutoContinue/releases/download/${{ github.ref_name }}/AutoContinue-Firefox-${{ github.ref_name }}.zip)
            - **Safari**: [AutoContinue-Safari-${{ github.ref_name }}.zip](https://github.com/sunnamed434/AutoContinue/releases/download/${{ github.ref_name }}/AutoContinue-Safari-${{ github.ref_name }}.zip)
            
            ### Source Code
            - **Source Code**: [AutoContinue-Source-${{ github.ref_name }}.zip](https://github.com/sunnamed434/AutoContinue/releases/download/${{ github.ref_name }}/AutoContinue-Source-${{ github.ref_name }}.zip)
            
            ## Installation
            
            1. Download the appropriate extension for your browser
            2. Extract the ZIP file
            3. Open your browser's extension management page
            4. Enable "Developer mode"
            5. Click "Load unpacked" and select the extracted folder
            
            ## Features
            
            - ✅ Automatically dismiss YouTube's "Continue watching?" popup
            - ✅ Works on YouTube and YouTube Music
            - ✅ Statistics tracking
            - ✅ Enable/disable toggle
            - ✅ Multi-language support
            
            ## Support
            
            - 🐛 [Report Issues](https://github.com/sunnamed434/AutoContinue/issues)
            - 💬 [Discussions](https://github.com/sunnamed434/AutoContinue/discussions)
            - 📖 [Documentation](https://github.com/sunnamed434/AutoContinue#readme)
          files: |
            release/AutoContinue-Chrome-${{ github.ref_name }}.zip
            release/AutoContinue-Firefox-${{ github.ref_name }}.zip
            release/AutoContinue-Safari-${{ github.ref_name }}.zip
            release/AutoContinue-Source-${{ github.ref_name }}.zip
          draft: false
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
